print("_______________DOOR POSITIONS__________________")
print("Front left door position: {0}".format(front_left_door_position))
print("Front right door position: {0}".format(front_right_door_position))
print("Rear left door position: {0}".format(rear_left_door_position))
print("Rear right door position: {0}".format(rear_right_door_position))
print("Boot position: {0}".format(boot_position))
print("Bonnet position: {0}".format(bonnet_position))


print("_______________DOOR LOCK STATUS__________________")
print("Overall door lock status: {0}".format(overall_door_lock_status))
print("Rear right door lock: {0}".format(rear_right_door_lock))
print("Rear left door lock: {0}".format(rear_left_door_lock))
print("Front right door position: {0}".format(front_right_door_lock))
print("Front left door position: {0}".format(front_left_door_lock))
print("Boot lock: {0}".format(boot_lock_status))
print("Bonnet lock: {0}".format(bonnet_lock))

print("_______________WARNINGS__________________")
print("Washer Fluid Warning?: {0}".format(washer_fluid_warn))
print("Brake Fluid Warning?: {0}".format(brake_fluid_warn))
print("Engine Coolant Warning?: {0}".format(engine_coolant_warn))
print("Exhaust Fluid Warning?: {0}".format(exhaust_fluid_warn))
print("Particulate Filter Warning?: {0}".format(part_filter_warn))

print("_______________TYRE STATUS__________________")
print("Rear left tyre status: {0}".format(rear_left_tyre_status))
print("Rear right tyre status: {0}".format(rear_right_tyre_status))
print("Front left tyre status: {0}".format(front_left_tyre_status))
print("Front right tyre status: {0}".format(front_right_tyre_status))

print("_______________TYRE PRESSURES__________________")
print("Rear left tyre pressure: {0}".format(rear_left_tyre_pres))
print("Rear right tyre pressure: {0}".format(rear_right_tyre_pres))
print("Front left tyre pressure: {0}".format(front_left_tyre_pres))
print("Front right tyre pressure: {0}".format(front_right_tyre_pres))

print("_______________WINDOW STATUS__________________")
print("Rear right window status: {0}".format(rear_right_window))
print("Rear left window status: {0}".format(rear_left_window))
print("Front right window status: {0}".format(front_right_window))
print("Front left window status: {0}".format(front_left_window))

print("_______________GENERAL__________________")
print("Mileage: {0}".format(mileage))
print("Distance to empty (in KM): {0}".format(distance_to_empty))
print("Panic Alarm Status: {0}".format(panic_alarm))
print("Theft Alarm Status: {0}".format(theft_alarm))
print("Crash Situation?: {0}".format(crash_situation))
print("Fuel Level in percent: {0}".format(fuel_level_percent))
print("Cab Open?: {0}".format(cab_open))